import type { Certificate, Project, Skill } from "@/types";

/**
 * Seed content shown until the matching Supabase table has rows.
 * This is the single source of truth for fallback data — the public sections
 * never embed their own copies.
 */

export const FALLBACK_SKILLS: Skill[] = [
  // Languages
  { id: "1",  name: "C / C++",                  category: "Languages", proficiency: 72, order_index: 1,  created_at: "" },
  { id: "2",  name: "Java",                      category: "Languages", proficiency: 72, order_index: 2,  created_at: "" },
  { id: "3",  name: "Python",                    category: "Languages", proficiency: 88, order_index: 3,  created_at: "" },
  { id: "4",  name: "JavaScript",                category: "Languages", proficiency: 90, order_index: 4,  created_at: "" },
  { id: "5",  name: "TypeScript",                category: "Languages", proficiency: 90, order_index: 5,  created_at: "" },
  // Frontend
  { id: "6",  name: "React.js",                  category: "Frontend",  proficiency: 92, order_index: 6,  created_at: "" },
  { id: "7",  name: "Next.js",                category: "Frontend",  proficiency: 90, order_index: 7,  created_at: "" },
  { id: "8",  name: "HTML5 / CSS3",              category: "Frontend",  proficiency: 92, order_index: 8,  created_at: "" },
  { id: "9",  name: "Tailwind CSS",              category: "Frontend",  proficiency: 90, order_index: 9,  created_at: "" },
  // Backend
  { id: "10", name: "Laravel",                   category: "Backend",   proficiency: 85, order_index: 10, created_at: "" },
  { id: "11", name: "Node.js / Express.js",      category: "Backend",   proficiency: 82, order_index: 11, created_at: "" },
  { id: "12", name: "FastAPI",                   category: "Backend",   proficiency: 78, order_index: 12, created_at: "" },
  { id: "13", name: "REST API Design",           category: "Backend",   proficiency: 80, order_index: 13, created_at: "" },
  // AI / ML
  { id: "14", name: "Scikit-learn",              category: "ML/AI",     proficiency: 78, order_index: 14, created_at: "" },
  { id: "15", name: "Pandas / NumPy",            category: "ML/AI",     proficiency: 80, order_index: 15, created_at: "" },
  { id: "16", name: "NLP / TF-IDF",             category: "ML/AI",     proficiency: 75, order_index: 16, created_at: "" },
  { id: "17", name: "Feature Engineering",       category: "ML/AI",     proficiency: 72, order_index: 17, created_at: "" },
  // Database
  { id: "18", name: "MySQL / PostgreSQL",        category: "Database",  proficiency: 85, order_index: 18, created_at: "" },
  { id: "19", name: "MongoDB",                   category: "Database",  proficiency: 80, order_index: 19, created_at: "" },
  { id: "20", name: "Supabase (Realtime)",       category: "Database",  proficiency: 80, order_index: 20, created_at: "" },
  // AR / VR
  { id: "21", name: "Unity",                     category: "AR/VR",     proficiency: 70, order_index: 21, created_at: "" },
  { id: "22", name: "XR Development",            category: "AR/VR",     proficiency: 68, order_index: 22, created_at: "" },
  // Security
  { id: "23", name: "Web Pentesting",            category: "Security",  proficiency: 72, order_index: 23, created_at: "" },
  { id: "24", name: "SQL Injection / OSINT",     category: "Security",  proficiency: 70, order_index: 24, created_at: "" },
  { id: "25", name: "Linux OS / Forensics",      category: "Security",  proficiency: 70, order_index: 25, created_at: "" },
  // Tools
  { id: "26", name: "Git / GitHub",              category: "Tools",     proficiency: 90, order_index: 26, created_at: "" },
  { id: "27", name: "VS Code / Postman",         category: "Tools",     proficiency: 88, order_index: 27, created_at: "" },
  { id: "28", name: "Vercel / Netlify",          category: "Tools",     proficiency: 80, order_index: 28, created_at: "" },
  { id: "29", name: "Prisma / Capacitor",        category: "Tools",     proficiency: 74, order_index: 29, created_at: "" },
];

export const FALLBACK_PROJECTS: Project[] = [
  {
    id: "1",
    title: "Internship Hub",
    problem: "Students, employers and administrators need one place to publish opportunities, apply for them and follow each application — in the language they are most comfortable with.",
    solution: "A role-based platform with separate student, employer and admin experiences, JWT authentication, application tracking and a fully bilingual (Bengali / English) interface, deployed on Vercel.",
    highlights: ["Role-based access for students, employers and admins", "JWT authentication", "Bilingual Bengali / English interface", "End-to-end application tracking", "Deployed on Vercel"],
    description: "Role-based job & internship platform for students, employers and admins with JWT auth, bilingual (Bengali/English) UI and application tracking. Deployed on Vercel.",
    tech_stack: ["React", "Laravel", "MySQL", "JWT", "Vercel"],
    category: "Full-Stack",
    featured: true,
    live_url: undefined,
    github_url: "https://github.com/hasib61714/internship-hub",
    order_index: 1,
    created_at: "",
    updated_at: "",
  },
  {
    id: "2",
    title: "Heart Disease Prediction",
    problem: "A heart-disease risk score is only useful if clinicians and patients can understand why the model produced it.",
    solution: "A FastAPI service serving a scikit-learn model, paired with a React frontend that shows the predicted risk together with explainable-AI insights, and exports the result as a PDF.",
    highlights: ["Explainable AI (XAI) insights alongside each prediction", "PDF export of results", "FastAPI backend with a React frontend", "Scikit-learn model for risk prediction"],
    description: "ML model with explainable AI (XAI) and PDF export. FastAPI backend + React frontend for predicting heart disease risk with model insights.",
    tech_stack: ["Python", "FastAPI", "React", "Scikit-learn"],
    category: "ML/AI",
    featured: true,
    live_url: undefined,
    github_url: "https://github.com/hasib61714/heart-disease-prediction",
    order_index: 2,
    created_at: "",
    updated_at: "",
  },
  {
    id: "3",
    title: "HairHub ERP System",
    problem: "Running a multi-factory business means keeping inventory, challans, cash flow and party settlements consistent in one system.",
    solution: "A production ERP with nine integrated modules, built with React, TypeScript and Supabase, made mobile-ready through Capacitor and live on Netlify.",
    highlights: ["9 integrated ERP modules", "Inventory, challan, cash flow and party settlement", "Mobile-ready via Capacitor", "Live in production on Netlify"],
    description: "Production 9-module ERP for multi-factory business — inventory, challan, cash flow, party settlement. Mobile-ready via Capacitor; live on Netlify.",
    tech_stack: ["React", "TypeScript", "Supabase", "Capacitor", "Tailwind CSS"],
    category: "Full-Stack",
    featured: true,
    live_url: "https://magenta-pasca-36250e.netlify.app",
    github_url: undefined,
    order_index: 3,
    created_at: "",
    updated_at: "",
  },
  {
    id: "4",
    title: "IMAP — AI Service Platform",
    problem: "People need a trustworthy way to find, book and follow service providers across the country in real time.",
    solution: "A national AI-powered service marketplace with live GPS tracking, real-time WebSocket chat and OTP authentication, delivering 19+ features end to end.",
    highlights: ["Live GPS tracking", "Real-time WebSocket chat", "OTP-based authentication", "19+ features", "AI-powered service matching"],
    description: "National AI-powered service marketplace with live GPS tracking, real-time WebSocket chat, OTP auth and 19+ features.",
    tech_stack: ["JavaScript", "AI", "GPS", "WebSocket", "Node.js"],
    category: "Full-Stack",
    featured: false,
    live_url: undefined,
    github_url: "https://github.com/hasib61714/imap-bangladesh",
    order_index: 4,
    created_at: "",
    updated_at: "",
  },
  {
    id: "5",
    title: "TrendHaus E-Commerce",
    problem: "An online store needs the full shopping journey — and the back-office tools behind it — in one coherent product.",
    solution: "A complete e-commerce platform covering cart, checkout, order tracking, wishlist and coupons, with an admin panel and inventory management.",
    highlights: ["Cart, checkout and order tracking", "Wishlist and coupons", "Admin panel", "Inventory management"],
    description: "Full e-commerce platform with cart, checkout, order tracking, wishlist, coupons, admin panel and inventory management.",
    tech_stack: ["React", "TypeScript", "Supabase", "Tailwind CSS"],
    category: "E-Commerce",
    featured: false,
    live_url: undefined,
    github_url: undefined,
    order_index: 5,
    created_at: "",
    updated_at: "",
  },
  {
    id: "6",
    title: "Fake News Detection",
    problem: "Misleading articles spread faster than they can be fact-checked by hand.",
    solution: "A text-classification pipeline that converts articles with TF-IDF and compares Naive Bayes, Logistic Regression, LinearSVC and Random Forest classifiers to find the most accurate model.",
    highlights: ["TF-IDF text features", "Four classifiers compared side by side", "Built with Scikit-learn, Pandas and NLP techniques"],
    description: "TF-IDF + multiple ML classifiers (Naive Bayes, Logistic Regression, LinearSVC, Random Forest) for fake news classification with high accuracy.",
    tech_stack: ["Python", "Scikit-learn", "NLP", "TF-IDF", "Pandas"],
    category: "ML/AI",
    featured: false,
    live_url: undefined,
    github_url: "https://github.com/hasib61714/Fake-News-Detector",
    order_index: 6,
    created_at: "",
    updated_at: "",
  },
];

export const FALLBACK_CERTS: Certificate[] = [
  {
    id: "1",
    title: "Software Engineer",
    issuer: "HackerRank",
    issue_date: "2026-04-01",
    description: "Credential ID: 842FC65F25FE",
    credential_url: "https://www.hackerrank.com/certificates/842FC65F25FE",
    created_at: "",
  },
  {
    id: "2",
    title: "Software Engineer Intern",
    issuer: "HackerRank",
    issue_date: "2026-04-01",
    description: "Credential ID: AE645963A25B",
    credential_url: "https://www.hackerrank.com/certificates/AE645963A25B",
    created_at: "",
  },
  {
    id: "3",
    title: "Frontend Developer (React)",
    issuer: "HackerRank",
    issue_date: "2026-04-01",
    description: "Credential ID: 77F03DAEDFC5",
    credential_url: "https://www.hackerrank.com/certificates/77F03DAEDFC5",
    created_at: "",
  },
  {
    id: "4",
    title: "Cyber Security & Ethical Hacking",
    issuer: "Arena Web Security",
    issue_date: "2024-03-01",
    description: "18-week certified programme — Verification: A47W1403S045",
    created_at: "",
  },
  {
    id: "5",
    title: "Job Ready: Employability Skills",
    issuer: "Wadhwani Foundation",
    issue_date: "2026-04-01",
    description: "Green University of Bangladesh · 75 hours",
    created_at: "",
  },
  {
    id: "6",
    title: "AR/VR Development Training",
    issuer: "Battery Low Interactive Ltd.",
    issue_date: "2026-01-01",
    description: "Hands-on AR/VR development training with live project work using Unity.",
    created_at: "",
  },
  {
    id: "7",
    title: "Machine Learning & Data Science",
    issuer: "Self-Directed / Project-Based",
    issue_date: "2024-01-01",
    description: "Project-based learning covering Scikit-learn, Pandas, NumPy, NLP, and feature engineering.",
    created_at: "",
  },
];
